

numFeatures = 3;
numResponses = 1;
numHiddenUnits = 125;

layers = [ ...
    sequenceInputLayer(numFeatures)
    lstmLayer(numHiddenUnits)
    fullyConnectedLayer(numResponses)
    regressionLayer];

options = trainingOptions('adam', ...
    'MaxEpochs',250, ...
    'GradientThreshold',1, ...
    'InitialLearnRate',0.005, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',125, ...
    'LearnRateDropFactor',0.2, ...
    'Verbose',0, ...
    'ValidationData',{Xte',Yte'},...
    'ValidationFrequency',1,...
    'ValidationPatience',5,...
    'Plots','training-progress');

net = trainNetwork(Xtr',Ytr',layers,options);